/*
 * allure-report-service
 *
 * Branch **HEAD**  Commit **1858ebdc07ef5d4e4615f9b1f2695e658df2e4ca**
 *
 * API version: 4.24.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package allure_api

type TestCaseCreateDto struct {
	ProjectId      int64                 `json:"projectId"`
	Name           string                `json:"name"`
	FullName       string                `json:"fullName,omitempty"`
	Description    string                `json:"description,omitempty"`
	Precondition   string                `json:"precondition,omitempty"`
	ExpectedResult string                `json:"expectedResult,omitempty"`
	Deleted        bool                  `json:"deleted,omitempty"`
	Automated      bool                  `json:"automated,omitempty"`
	External       bool                  `json:"external,omitempty"`
	TestLayerId    int64                 `json:"testLayerId,omitempty"`
	StatusId       int64                 `json:"statusId,omitempty"`
	WorkflowId     int64                 `json:"workflowId,omitempty"`
	Scenario       *TestCaseScenarioDto  `json:"scenario,omitempty"`
	Tags           []TestTagDto          `json:"tags,omitempty"`
	Links          []ExternalLinkDto     `json:"links,omitempty"`
	CustomFields   []CustomFieldValueDto `json:"customFields,omitempty"`
	Members        []MemberDto           `json:"members,omitempty"`
}
