/*
 * allure-report-service
 *
 * Branch **HEAD**  Commit **1858ebdc07ef5d4e4615f9b1f2695e658df2e4ca**
 *
 * API version: 4.24.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package allure_api

type TestCaseExportField string

// List of TestCaseExportField
const (
	ALLURE_ID_TestCaseExportField       TestCaseExportField = "allure_id"
	NAME_TestCaseExportField            TestCaseExportField = "name"
	FULL_NAME_TestCaseExportField       TestCaseExportField = "full_name"
	AUTOMATED_TestCaseExportField       TestCaseExportField = "automated"
	DESCRIPTION_TestCaseExportField     TestCaseExportField = "description"
	PRECONDITION_TestCaseExportField    TestCaseExportField = "precondition"
	EXPECTED_RESULT_TestCaseExportField TestCaseExportField = "expected_result"
	STATUS_TestCaseExportField          TestCaseExportField = "status"
	SCENARIO_TestCaseExportField        TestCaseExportField = "scenario"
	ISSUE_TestCaseExportField           TestCaseExportField = "issue"
	TAG_TestCaseExportField             TestCaseExportField = "tag"
	LINK_TestCaseExportField            TestCaseExportField = "link"
	CUSTOM_FIELD_TestCaseExportField    TestCaseExportField = "custom_field"
	ROLE_TestCaseExportField            TestCaseExportField = "role"
	EXAMPLE_TestCaseExportField         TestCaseExportField = "example"
	PARAMETER_TestCaseExportField       TestCaseExportField = "parameter"
)
