/*
 * allure-report-service
 *
 * Branch **HEAD**  Commit **1858ebdc07ef5d4e4615f9b1f2695e658df2e4ca**
 *
 * API version: 4.24.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package allure_api

type ScenarioStepCreateDto struct {
	ParentId       int64  `json:"parentId,omitempty"`
	TestCaseId     int64  `json:"testCaseId,omitempty"`
	Body           string `json:"body,omitempty"`
	ExpectedResult string `json:"expectedResult,omitempty"`
	AttachmentId   int64  `json:"attachmentId,omitempty"`
	SharedStepId   int64  `json:"sharedStepId,omitempty"`
}
