/*
 * allure-report-service
 *
 * Branch **HEAD**  Commit **1858ebdc07ef5d4e4615f9b1f2695e658df2e4ca**
 *
 * API version: 4.24.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package allure_api

type TestCaseCsvPreviewOptions struct {
	WithHeaders      bool                                         `json:"withHeaders,omitempty"`
	AutoDetectFormat bool                                         `json:"autoDetectFormat,omitempty"`
	ColumnSeparator  string                                       `json:"columnSeparator,omitempty"`
	EscapeChar       string                                       `json:"escapeChar,omitempty"`
	QuoteChar        string                                       `json:"quoteChar,omitempty"`
	WorkflowId       int64                                        `json:"workflowId,omitempty"`
	StatusId         int64                                        `json:"statusId,omitempty"`
	LayerId          int64                                        `json:"layerId,omitempty"`
	Mapping          []OneOfTestCaseCsvPreviewOptionsMappingItems `json:"mapping,omitempty"`
	RowNum           int32                                        `json:"rowNum,omitempty"`
}
