/*
 * allure-report-service
 *
 * Branch **HEAD**  Commit **1858ebdc07ef5d4e4615f9b1f2695e658df2e4ca**
 *
 * API version: 4.24.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package allure_api

type IntegrationOperationTypeDto string

// List of IntegrationOperationTypeDto
const (
	ISSUE_CREATE_IntegrationOperationTypeDto        IntegrationOperationTypeDto = "issue_create"
	ISSUE_EXPORT_LAUNCH_IntegrationOperationTypeDto IntegrationOperationTypeDto = "issue_export_launch"
	ISSUE_SUGGEST_IntegrationOperationTypeDto       IntegrationOperationTypeDto = "issue_suggest"
	ISSUE_SYNC_IntegrationOperationTypeDto          IntegrationOperationTypeDto = "issue_sync"
	JOB_RUN_IntegrationOperationTypeDto             IntegrationOperationTypeDto = "job_run"
	JOB_SUGGEST_IntegrationOperationTypeDto         IntegrationOperationTypeDto = "job_suggest"
	JOB_SYNC_IntegrationOperationTypeDto            IntegrationOperationTypeDto = "job_sync"
	TMS_SYNC_IntegrationOperationTypeDto            IntegrationOperationTypeDto = "tms_sync"
	TEST_KEY_SUGGEST_IntegrationOperationTypeDto    IntegrationOperationTypeDto = "test_key_suggest"
	TEST_KEY_SYNC_IntegrationOperationTypeDto       IntegrationOperationTypeDto = "test_key_sync"
)
