/*
 * allure-report-service
 *
 * Branch **HEAD**  Commit **1858ebdc07ef5d4e4615f9b1f2695e658df2e4ca**
 *
 * API version: 4.24.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package allure_api

type IntegrationRoutineTypeDto string

// List of IntegrationRoutineTypeDto
const (
	ENDPOINT_IntegrationRoutineTypeDto     IntegrationRoutineTypeDto = "endpoint"
	ISSUE_URL_IntegrationRoutineTypeDto    IntegrationRoutineTypeDto = "issue_url"
	TEST_KEY_URL_IntegrationRoutineTypeDto IntegrationRoutineTypeDto = "test_key_url"
	WEBHOOK_IntegrationRoutineTypeDto      IntegrationRoutineTypeDto = "webhook"
)
