/*
 * allure-report-service
 *
 * Branch **HEAD**  Commit **1858ebdc07ef5d4e4615f9b1f2695e658df2e4ca**
 *
 * API version: 4.24.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package allure_api

type TestCaseDto struct {
	Id                 int64             `json:"id,omitempty"`
	ProjectId          int64             `json:"projectId,omitempty"`
	Name               string            `json:"name,omitempty"`
	FullName           string            `json:"fullName,omitempty"`
	Description        string            `json:"description,omitempty"`
	DescriptionHtml    string            `json:"descriptionHtml,omitempty"`
	Precondition       string            `json:"precondition,omitempty"`
	PreconditionHtml   string            `json:"preconditionHtml,omitempty"`
	ExpectedResult     string            `json:"expectedResult,omitempty"`
	ExpectedResultHtml string            `json:"expectedResultHtml,omitempty"`
	Hash               string            `json:"hash,omitempty"`
	Deleted            bool              `json:"deleted,omitempty"`
	Editable           bool              `json:"editable,omitempty"`
	Automated          bool              `json:"automated,omitempty"`
	External           bool              `json:"external,omitempty"`
	TestLayer          *TestLayerDto     `json:"testLayer,omitempty"`
	Tags               []TestTagDto      `json:"tags,omitempty"`
	Links              []ExternalLinkDto `json:"links,omitempty"`
	Status             *StatusDto        `json:"status,omitempty"`
	Workflow           *WorkflowRowDto   `json:"workflow,omitempty"`
	CreatedDate        int64             `json:"createdDate,omitempty"`
	LastModifiedDate   int64             `json:"lastModifiedDate,omitempty"`
	CreatedBy          string            `json:"createdBy,omitempty"`
	LastModifiedBy     string            `json:"lastModifiedBy,omitempty"`
}
