/*
 * allure-report-service
 *
 * Branch **HEAD**  Commit **1858ebdc07ef5d4e4615f9b1f2695e658df2e4ca**
 *
 * API version: 4.24.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package allure_api

type LaunchDiffStatusChangeDto struct {
	TestCaseId  int64       `json:"testCaseId,omitempty"`
	FromId      int64       `json:"fromId,omitempty"`
	FromName    string      `json:"fromName,omitempty"`
	FromStatus  *TestStatus `json:"fromStatus,omitempty"`
	FromMessage string      `json:"fromMessage,omitempty"`
	FromTrace   string      `json:"fromTrace,omitempty"`
	ToId        int64       `json:"toId,omitempty"`
	ToName      string      `json:"toName,omitempty"`
	ToStatus    *TestStatus `json:"toStatus,omitempty"`
	ToMessage   string      `json:"toMessage,omitempty"`
	ToTrace     string      `json:"toTrace,omitempty"`
}
