/*
 * allure-report-service
 *
 * Branch **HEAD**  Commit **1858ebdc07ef5d4e4615f9b1f2695e658df2e4ca**
 *
 * API version: 4.24.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package allure_api

type TestCaseImportField string

// List of TestCaseImportField
const (
	SKIP_TestCaseImportField            TestCaseImportField = "skip"
	ALLURE_ID_TestCaseImportField       TestCaseImportField = "allure_id"
	NAME_TestCaseImportField            TestCaseImportField = "name"
	FULL_NAME_TestCaseImportField       TestCaseImportField = "full_name"
	DESCRIPTION_TestCaseImportField     TestCaseImportField = "description"
	PRECONDITION_TestCaseImportField    TestCaseImportField = "precondition"
	EXPECTED_RESULT_TestCaseImportField TestCaseImportField = "expected_result"
	SCENARIO_TestCaseImportField        TestCaseImportField = "scenario"
	CUSTOM_FIELD_TestCaseImportField    TestCaseImportField = "custom_field"
	ROLE_TestCaseImportField            TestCaseImportField = "role"
	PARAMETER_TestCaseImportField       TestCaseImportField = "parameter"
	TAG_TestCaseImportField             TestCaseImportField = "tag"
	ISSUE_TestCaseImportField           TestCaseImportField = "issue"
	TEST_KEY_TestCaseImportField        TestCaseImportField = "test_key"
	LINK_TestCaseImportField            TestCaseImportField = "link"
)
