/*
 * allure-report-service
 *
 * Branch **HEAD**  Commit **1858ebdc07ef5d4e4615f9b1f2695e658df2e4ca**
 *
 * API version: 4.24.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package allure_api

type LaunchPdfPart string

// List of LaunchPdfPart
const (
	HEADER_LaunchPdfPart         LaunchPdfPart = "header"
	TITLE_LaunchPdfPart          LaunchPdfPart = "title"
	STATISTIC_LaunchPdfPart      LaunchPdfPart = "statistic"
	SUMMARY_LaunchPdfPart        LaunchPdfPart = "summary"
	TR_BY_STATUSES_LaunchPdfPart LaunchPdfPart = "trByStatuses"
	DETAILS_LaunchPdfPart        LaunchPdfPart = "details"
	TC_DETAILS_LaunchPdfPart     LaunchPdfPart = "tcDetails"
	FOOTER_LaunchPdfPart         LaunchPdfPart = "footer"
)
