/*
 * allure-report-service
 *
 * Branch **HEAD**  Commit **1858ebdc07ef5d4e4615f9b1f2695e658df2e4ca**
 *
 * API version: 4.24.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package allure_api

type IntegrationFieldsFormDto struct {
	GlobalFields               []OneOfIntegrationFieldsFormDtoGlobalFieldsItems         `json:"globalFields,omitempty"`
	GlobalFieldsValues         map[string]interface{}                                   `json:"globalFieldsValues,omitempty"`
	DefaultProjectFields       []OneOfIntegrationFieldsFormDtoDefaultProjectFieldsItems `json:"defaultProjectFields,omitempty"`
	DefaultProjectFieldsValues map[string]interface{}                                   `json:"defaultProjectFieldsValues,omitempty"`
	DefaultSecretFields        []OneOfIntegrationFieldsFormDtoDefaultSecretFieldsItems  `json:"defaultSecretFields,omitempty"`
	DefaultSecretSpecified     bool                                                     `json:"defaultSecretSpecified,omitempty"`
}
