/*
 * allure-report-service
 *
 * Branch **HEAD**  Commit **1858ebdc07ef5d4e4615f9b1f2695e658df2e4ca**
 *
 * API version: 4.24.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package allure_api

type TestCaseRowDto struct {
	Id        int64         `json:"id,omitempty"`
	Name      string        `json:"name,omitempty"`
	Status    *StatusDto    `json:"status,omitempty"`
	TestLayer *TestLayerDto `json:"testLayer,omitempty"`
	Automated bool          `json:"automated,omitempty"`
}
